# Generated by Django 6.0.6 on 2026-06-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('autonomo', 'Autônomo'), ('imobiliaria', 'Imobiliária')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DemandaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(choices=[('casa', 'Casa'), ('apartamento', 'Apartamento'), ('cobertura', 'Cobertura'), ('terreno', 'Terreno'), ('comercial', 'Comercial')], max_length=30)),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('locacao', 'Locação')], max_length=20)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('dormitorios', models.IntegerField(blank=True, null=True)),
                ('area_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('elevador', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('indiferente', 'Indiferente')], default='indiferente', max_length=15)),
                ('andar_maximo', models.IntegerField(blank=True, null=True)),
                ('varanda', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('indiferente', 'Indiferente')], default='indiferente', max_length=15)),
                ('posicao_solar', models.CharField(choices=[('nascente', 'Nascente'), ('sul', 'Sul'), ('poente', 'Poente'), ('indiferente', 'Indiferente')], default='indiferente', max_length=15)),
                ('condominio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vagas', models.IntegerField(blank=True, null=True)),
                ('vagas_cobertas', models.IntegerField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imoveis.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('finalidade', models.CharField(choices=[('venda', 'Venda'), ('locacao', 'Locação')], max_length=20)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('reservado', 'Reservado'), ('vendido', 'Vendido'), ('alugado', 'Alugado')], max_length=20)),
                ('dormitorios', models.IntegerField(default=0)),
                ('suites', models.IntegerField(default=0)),
                ('banheiros', models.IntegerField(default=0)),
                ('vagas', models.IntegerField(default=0)),
                ('vagas_cobertas', models.IntegerField(default=0)),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_construida', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('andar', models.IntegerField(blank=True, null=True)),
                ('elevador', models.BooleanField(default=False)),
                ('varanda', models.BooleanField(default=False)),
                ('posicao_solar', models.CharField(blank=True, choices=[('nascente', 'Nascente'), ('sul', 'Sul'), ('poente', 'Poente')], max_length=20, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.categoria')),
                ('corretor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imoveis.corretor')),
                ('infraestrutura', models.ManyToManyField(blank=True, to='imoveis.infraestrutura')),
            ],
        ),
        migrations.CreateModel(
            name='FotoImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='imoveis/')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='imoveis.imovel')),
            ],
        ),
    ]
