# Generated by Django 6.0.6 on 2026-06-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandacliente',
            name='bairros',
            field=models.CharField(blank=True, help_text='Bairros separados por vírgula', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='demandacliente',
            name='infraestrutura',
            field=models.ManyToManyField(blank=True, to='imoveis.infraestrutura'),
        ),
        migrations.AddField(
            model_name='demandacliente',
            name='regiao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demandacliente',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('atendida', 'Atendida')], default='aberta', max_length=20),
        ),
        migrations.AlterField(
            model_name='demandacliente',
            name='vagas_cobertas',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('indiferente', 'Indiferente')], default='indiferente', max_length=15),
        ),
    ]
