# Generated by Django 6.0.6 on 2026-06-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_demandacliente_bairros_demandacliente_infraestrutura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandacliente',
            name='andar_maximo',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='area_minima',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='condominio_maximo',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='elevador',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='regiao',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='vagas_cobertas',
        ),
        migrations.RemoveField(
            model_name='demandacliente',
            name='varanda',
        ),
        migrations.AddField(
            model_name='demandacliente',
            name='cidade',
            field=models.CharField(choices=[('João Pessoa', 'João Pessoa'), ('Cabedelo', 'Cabedelo')], default='João Pessoa', max_length=50),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(choices=[('João Pessoa', 'João Pessoa'), ('Cabedelo', 'Cabedelo')], default='João Pessoa', max_length=50),
        ),
    ]
