# Generated by Django 6.0.6 on 2026-06-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_remove_demandacliente_andar_maximo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandacliente',
            name='atendida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
