# Generated by Django 6.0.6 on 2026-06-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_imovel_tipo_finalizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandacliente',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('atendida', 'Finalizada')], default='aberta', max_length=20),
        ),
    ]
