# Generated by Django 6.0.6 on 2026-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_fotoimovel_imagem_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='andar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Andar do imóvel'),
        ),
    ]
