# Generated by Django 6.0.6 on 2026-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0014_add_imovel_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandacliente',
            name='vagas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Garagem mínima'),
        ),
        migrations.AlterField(
            model_name='demandacliente',
            name='vagas_cobertas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Garagens cobertas mínimas'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas',
            field=models.IntegerField(default=0, verbose_name='Garagem'),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='vagas_cobertas',
            field=models.IntegerField(default=0, verbose_name='Garagens cobertas'),
        ),
    ]
