# Generated by Django 6.0.6 on 2026-06-09 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0015_alter_demandacliente_vagas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandacliente',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, help_text='Usuários que colaboram nessa demanda.', related_name='demandas_colaboradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
