# Generated by Django 6.0.6 on 2026-06-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0017_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='finalidade',
            field=models.CharField(choices=[('venda', 'Venda'), ('locacao', 'Locação'), ('compra', 'Compra')], max_length=20),
        ),
    ]
